function [fitresult, gof, xData, yData] = createFitRightSensor(x, yRight)
%CREATEFIT(X,YRIGHT)
%  Create a fit.
%
%  Data for 'RightADCfit' fit:
%      X Input : x
%      Y Output: yRight
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2021 13:59:26


%% Fit: 'RightADCfit'.
[xData, yData] = prepareCurveData( x, yRight );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

h = figure();
h.WindowStyle = 'docked';
% Plot fit with data.
% figure( 'Name', 'RightADCfit' );
h = plot( fitresult, xData, yData );
legend( h, 'yRight vs. x', 'RightADCfit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'yRight', 'Interpreter', 'none' );
grid on


