function [fitresult, gof, xData, yData] = createFitLeftSensor(x, yLeft)
%CREATEFIT(X,YLEFT)
%  Create a fit.
%
%  Data for 'LeftADCfit' fit:
%      X Input : x
%      Y Output: yLeft
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Mar-2021 13:55:23


%% Fit: 'LeftADCfit'.
[xData, yData] = prepareCurveData( x, yLeft );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

h = figure();
h.WindowStyle = 'docked';
% Plot fit with data.
% figure( 'Name', 'LeftADCfit' );
h = plot( fitresult, xData, yData );
legend( h, 'yLeft vs. x', 'LeftADCfit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'yLeft', 'Interpreter', 'none' );
grid on

end
